### ISSUE TITLE
FedEx tracking url leads to 404 page

### ISSUE THREAD

**Issue by mfrazie2** [niradler/tracking-number-validation#11]
When given a valid tracking number, the generated url leads to a 404 page. 

![Screen Shot 2022-06-07 at 9 13 31 AM](https://user-images.githubusercontent.com/13042612/172416830-1f5b58c4-f5a7-47cb-81aa-d5e4dd5497d4.png)

Previously, I was using this FedEx link as a template and substituting in the tracking number: `https://www.fedex.com/fedextrack/?tracknumbers=${trackingNumber}`.

**Comment by niradler** [comment]
@mfrazie2 updated thanks for letting me know.
