### ISSUE TITLE
Fedex tracking not recognized

### ISSUE THREAD

**Issue by ionafan2** [niradler/tracking-number-validation#6]
Hi,
This kind FedEx tracking `9622080430002481027200399594546820` is not recognized as a FedEx one.

**Comment by niradler** [comment]
@danielbonnells sorry i miss it, can you provide a reference showing this is legal tracking ? and i will add it 🥇

**Comment by niradler** [comment]
https://github.com/niradler/tracking-number-validation/pull/8
